import Content from "../../HOME/Content";
import Code from "../../HOME/Code"
import Buttons from "../../Buttons/Buttons";
import { Link, useNavigate } from "react-router-dom";
import React, { useState, useEffect} from "react";

const AdminHome = () => {
    const navigate = useNavigate();
    const [username, setUsername] = useState("");

    useEffect(() => {
        const role = localStorage.getItem("userRole");
        const name = localStorage.getItem("username");
        if (role !== "admin") {
            navigate("/")
        } else {
            setUsername(name || "");
        }
    }, [navigate]);

    const handleLogout = () => {
        localStorage.clear();
        navigate("/");
    };


  return (
    <div className="flex-1 flex h-full w-full pt-20 "> {/* pt-20 ให้ space สำหรับ NavBar ล็อค */}
      {/* Center Panel */}
      <div className="flex-1 flex flex-col  m-8 rounded-3xl ">
        {/* Top Center */}
        <div className="h-1/8 bg-transparent m-12 p-4  " >
          <Code />
        </div>
        
        {/* Bottom Center */}
        <div className="flex-1  h-64 overflow-auto m-8 p-6 gap-11 bg-gray-800 rounded-3xl ">
          
         <Content
            imageUrl="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSgQJolH1qSi-mDOWfYmceIBY6Bjf2sxUlI026bF3FtyV5_75tzIZz3Vd7kK3xVW5iKCjM1D_nIJ7WNZUjtIxBNVVX0IMuSdrIN2ImOww"
            title="Admin"
            description="สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            dddddddddddddddddddddddddddddddddddddd
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา..."
          />
          <Content
            imageUrl="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSgQJolH1qSi-mDOWfYmceIBY6Bjf2sxUlI026bF3FtyV5_75tzIZz3Vd7kK3xVW5iKCjM1D_nIJ7WNZUjtIxBNVVX0IMuSdrIN2ImOww"
            title="Welcome to the Home Page"
            description="สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา..."
          />

          <Content
            imageUrl="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSgQJolH1qSi-mDOWfYmceIBY6Bjf2sxUlI026bF3FtyV5_75tzIZz3Vd7kK3xVW5iKCjM1D_nIJ7WNZUjtIxBNVVX0IMuSdrIN2ImOww"
            title="Welcome to the Home Page"
            description="สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            dddddddddddddddddddddddddddddddd
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา..."
          />

          <Content
            imageUrl="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSgQJolH1qSi-mDOWfYmceIBY6Bjf2sxUlI026bF3FtyV5_75tzIZz3Vd7kK3xVW5iKCjM1D_nIJ7WNZUjtIxBNVVX0IMuSdrIN2ImOww"
            title="Welcome to the Home Page"
            description="สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา...
            สวัสดี ยินดีต้อนรับสู่หน้าแรกของเว็บไซต์ของเรา..."
          />
          
        </div>
        
      </div>

      {/* Right Panel */}
      
      <div className="w-1/5 flex flex-col ">
        <div className="flex flex-col gap-4 justify-center items-center m-4 bg-gray-800/60 p-5 text-red-500 rounded-3xl">
        <div>
            <p>
                Hi, {username}
            </p>
        </div>
          <Buttons variant="logout">
            <Link to="/PROFILE/Login">
            Logout
            </Link>
          </Buttons>
        </div>
        <div className="flex-1 m-4 bg-gray-800/80 p-4 text-red-500">
          ขวา
        </div>
      </div>
    </div>
  )
}

export default AdminHome;
